variables:
  GLUON_RELEASE: "v2019.1.x-ibss-weekly"
  GLUON_BRANCH: "v2019.1.x"

image: git.freifunk-koeln.de:5050/ff-koeln/gluon-docker-build/gluon-build

stages:
  - build

build:
  stage: build
  before_script:
  - mkdir -p downloads/
  script:
  - make FORCE_UNSAFE_CONFIGURE=1 CC='ccache gcc' DL_DIR=${PWD}/downloads
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY_RELEASE_FFKOELN" | base64 -d)
  - xz dist/*.txt
  - rsync -e "ssh -o StrictHostKeyChecking=no" --delete -Ha dist/ gitlabci@files-v6.freifunk-koeln.de:/var/www/html/${GLUON_RELEASE}
