image: debian:stable


build:
  stage: build
  before_script:
  - export LANG=C.UTF-8
  - apt-get update
  - apt-get install -y build-essential xzip wget git ca-certificates gawk file libpng-dev curl sudo unzip libncurses5-dev python subversion rsync libssl-dev ccache
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache
  - mkdir downloads/
  script:
  - make FORCE_UNSAFE_CONFIGURE=1 CC='ccache gcc' DL_DIR=${PWD}/downloads
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
  - rsync -e "ssh -4 -o StrictHostKeyChecking=no -p 2310" --delete -Havc dist/ gluon-weekly@www1.kbu.freifunk.net:/space/files/gluon-weekly/2016.2/
  only:
  - master
  cache:
    paths:
    - ccache/
    - downloads/
    - /var/cache/apt/archives/
