image: debian:stable


build:
  stage: build
  before_script:
  - export LANG=C.UTF-8
  - apt-get update
  - apt-get install -y build-essential xzip wget git ca-certificates gawk file libpng-dev curl sudo unzip libncurses5-dev python subversion rsync libssl-dev ccache xz-utils gettext-base
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache
  - mkdir -p downloads/
  script:
  - make FORCE_UNSAFE_CONFIGURE=1 CC='ccache gcc' DL_DIR=${PWD}/downloads
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY_RELEASE_FIELDTRACKS" | base64 -d)
  - xz dist/*.txt
  - rsync -e "ssh -4 -o StrictHostKeyChecking=no -p 2200" --delete -Ha dist/ fieldtracks@fieldtracks.org:/var/www/vhosts/fieldtracks.org/httpdocs/gluon
  only:
  - fieldtracks
