image: debian:stable


build:
  stage: build
  before_script:
  - export LANG=C.UTF-8
  - apt-get update
  - apt-get install -y build-essential xzip wget git ca-certificates gawk file libpng-dev curl sudo unzip libncurses5-dev python subversion rsync libssl-dev ccache xz-utils
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache
  - mkdir -p downloads/
  script:
  - make FORCE_UNSAFE_CONFIGURE=1 CC='ccache gcc' DL_DIR=${PWD}/downloads
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY_RELEASE" | base64 -d)
  - rsync -e "ssh -4 -o StrictHostKeyChecking=no -p 2310" --delete -Havc dist/ gluon-release@www1.kbu.freifunk.net:/space/files/gluon-weekly/2017.1
  - xz out.txt
  - xz err.txt
  only:
  - master
  artifacts:
    paths:
    - out.txt.xz
    - err.txt.xz

  cache:
    paths:
    - ccache/
